"""add_updated_at_and_status_to_messages

Revision ID: 83baeb9dda89
Revises: 30b207b44e82
Create Date: 2026-07-08 15:53:11.736590

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "83baeb9dda89"
down_revision: str | Sequence[str] | None = "30b207b44e82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    message_status_enum = postgresql.ENUM("DELIVERED", "READ", name="messagestatus")
    message_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "messages",
        sa.Column(
            "message_status",
            sa.Enum("DELIVERED", "READ", name="messagestatus"),
            server_default="DELIVERED",
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "updated_at")
    op.drop_column("messages", "message_status")
    message_status_enum = postgresql.ENUM("DELIVERED", "READ", name="messagestatus")
    message_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
