"""create_pagination_messages_index

Revision ID: 30b207b44e82
Revises: 79defcccfeaf
Create Date: 2026-05-24 14:18:24.510520

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30b207b44e82"
down_revision: str | Sequence[str] | None = "79defcccfeaf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_messages_pagination",
        "messages",
        [sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_messages_pagination", table_name="messages")
    # ### end Alembic commands ###
