"""add_creator_to_chats

Revision ID: 85c6a556397c
Revises: fcd111a981fe
Create Date: 2026-04-26 16:03:23.636989

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85c6a556397c"
down_revision: str | Sequence[str] | None = "fcd111a981fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "chats_user_id_fkey", "chats", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chats_user_id_fkey", "chats", type_="foreignkey")
    op.drop_column("chats", "user_id")
    # ### end Alembic commands ###
