"""add_invited_chat_user

Revision ID: 4404420b81d0
Revises: 671612441df7
Create Date: 2026-05-14 21:33:57.276081

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4404420b81d0"
down_revision: str | Sequence[str] | None = "671612441df7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_users", sa.Column("invited_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "chat_users_invited_id_fkey",
        "chat_users",
        "users",
        ["invited_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chat_users_invited_id_fkey", "chat_users", type_="foreignkey")
    op.drop_column("chat_users", "invited_id")
    # ### end Alembic commands ###
