"""rename_author_to_sender_messages

Revision ID: 79defcccfeaf
Revises: 4404420b81d0
Create Date: 2026-05-17 11:49:46.999823

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79defcccfeaf"
down_revision: str | Sequence[str] | None = "4404420b81d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("sender_id", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("messages_author_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_sender_id_fkey",
        "messages",
        "users",
        ["sender_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("messages", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("messages_sender_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_author_id_fkey"),
        "messages",
        "users",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("messages", "sender_id")
    # ### end Alembic commands ###
